# Generated by Django 3.0.8 on 2020-07-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrequest',
            name='sent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
